/**
 * Preview-snapshot integrity.
 *
 * `demo-data.ts` is regenerated by hand from a seeded API, which makes it the
 * easiest thing in the repo to get quietly wrong: a screen can render fine
 * while a link inside it points at a record the snapshot does not contain.
 * That already happened once — a transaction appeared in the list with no
 * detail entry, so clicking it 404'd only in preview, which is exactly where
 * nobody is running the API to notice.
 *
 * These tests check two things:
 *   1. every snapshot still satisfies the contract schema (drift between the
 *      API shape and the snapshot is otherwise invisible until runtime), and
 *   2. every link the UI can build from one snapshot resolves in another.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import {
  accountSummary,
  householdDetail,
  workQueues,
  txnSummary,
  txnDetail,
  meProfile,
  teamRoster,
  documentRow,
  documentTemplate,
  billingOverview,
  complianceOverview,
  claimRow,
  policyListRow,
  marketRow,
} from '@insurimple/contracts';
import {
  DEMO_ACCOUNTS,
  DEMO_HOUSEHOLDS,
  DEMO_QUEUES,
  DEMO_TXNS,
  DEMO_TXN_DETAIL,
  DEMO_ME,
  DEMO_TEAM,
  DEMO_DOCUMENTS,
  DEMO_TEMPLATES,
  DEMO_BILLING,
  DEMO_COMPLIANCE,
  DEMO_CLAIMS,
  DEMO_POLICIES,
  DEMO_MARKETS,
} from './demo-data.ts';

/** zod's error is unreadable in a bare assert; surface the first issue. */
function parses(schema: { safeParse: (v: unknown) => { success: boolean; error?: unknown } }, value: unknown, label: string) {
  const r = schema.safeParse(value);
  if (!r.success) {
    const issues = (r.error as { issues?: { path: (string | number)[]; message: string }[] })?.issues ?? [];
    const first = issues[0];
    assert.fail(
      `${label} does not match its contract: ${first ? `${first.path.join('.')} — ${first.message}` : 'unknown'}`,
    );
  }
}

describe('snapshots match the contracts', () => {
  test('accounts', () => {
    for (const a of DEMO_ACCOUNTS) parses(accountSummary, a, `account ${a.id}`);
  });
  test('household details', () => {
    for (const [id, h] of Object.entries(DEMO_HOUSEHOLDS)) parses(householdDetail, h, `household ${id}`);
  });
  test('work queues', () => parses(workQueues, DEMO_QUEUES, 'queues'));
  test('transactions', () => {
    for (const t of DEMO_TXNS) parses(txnSummary, t, `txn ${t.id}`);
    for (const [id, d] of Object.entries(DEMO_TXN_DETAIL)) parses(txnDetail, d, `txn detail ${id}`);
  });
  test('profile and team', () => {
    parses(meProfile, DEMO_ME, 'me');
    parses(teamRoster, DEMO_TEAM, 'team');
  });
  test('documents', () => {
    for (const d of DEMO_DOCUMENTS) parses(documentRow, d, `document ${d.id}`);
    for (const t of DEMO_TEMPLATES) parses(documentTemplate, t, `template ${t.code}`);
  });
  test('billing and compliance', () => {
    parses(billingOverview, DEMO_BILLING, 'billing');
    parses(complianceOverview, DEMO_COMPLIANCE, 'compliance');
  });
  test('claims, policies, markets', () => {
    for (const c of DEMO_CLAIMS) parses(claimRow, c, `claim ${c.id}`);
    for (const p of DEMO_POLICIES) parses(policyListRow, p, `policy ${p.id}`);
    for (const m of DEMO_MARKETS) parses(marketRow, m, `market ${m.id}`);
  });
});

describe('every link the UI can build resolves', () => {
  test('a transaction in the list has a detail record', () => {
    for (const t of DEMO_TXNS) {
      assert.ok(
        DEMO_TXN_DETAIL[t.id],
        `/transactions/${t.id} is reachable from the list but has no detail — it would 404 in preview`,
      );
    }
  });

  test('an account in the book has a household record', () => {
    for (const a of DEMO_ACCOUNTS) {
      assert.ok(
        DEMO_HOUSEHOLDS[a.id],
        `/households/${a.id} is reachable from the book but has no detail`,
      );
    }
  });

  test('a claim links to a transaction that exists', () => {
    for (const c of DEMO_CLAIMS) {
      if (c.txn_id) {
        assert.ok(DEMO_TXN_DETAIL[c.txn_id], `claim ${c.claim_number} links to a missing transaction`);
      }
    }
  });

  test('a work-queue row links to a household that exists', () => {
    for (const a of DEMO_QUEUES.activities) {
      if (a.account_id) {
        assert.ok(DEMO_HOUSEHOLDS[a.account_id], `activity "${a.title}" links to a missing household`);
      }
    }
    for (const r of DEMO_QUEUES.renewals) {
      assert.ok(DEMO_HOUSEHOLDS[r.account_id], `renewal ${r.policy_id} links to a missing household`);
    }
    for (const s of DEMO_QUEUES.suspense) {
      assert.ok(DEMO_HOUSEHOLDS[s.account_id], `suspense ${s.reference} links to a missing household`);
    }
  });

  test('a compliance exception links to something that exists', () => {
    const x = DEMO_COMPLIANCE.exceptions;
    for (const t of x.unsigned_transactions) {
      assert.ok(DEMO_TXN_DETAIL[t.id], `unsigned txn ${t.reference} links to a missing transaction`);
    }
    for (const s of x.unacknowledged_submissions) {
      assert.ok(DEMO_TXN_DETAIL[s.id], `unacknowledged ${s.reference} links to a missing transaction`);
    }
    for (const g of x.consent_gaps) {
      assert.ok(DEMO_HOUSEHOLDS[g.account_id], `consent gap ${g.account_name} links to a missing household`);
    }
  });

  test('a policy row links to a household that exists', () => {
    for (const p of DEMO_POLICIES) {
      assert.ok(DEMO_HOUSEHOLDS[p.account_id], `policy ${p.policy_number} links to a missing household`);
    }
  });

  test('the rating screen can only offer policies that exist', () => {
    const known = new Set(Object.values(DEMO_HOUSEHOLDS).flatMap((h) => h.policies.map((p) => p.id)));
    for (const m of DEMO_MARKETS) {
      assert.ok(m.carrier_name, 'a market must name its carrier');
    }
    assert.ok(known.size > 0, 'the snapshot must contain policies to rate');
  });
});

describe('the snapshot never passes as live data (invariant 7)', () => {
  test('it is a single tenant book, not a mix', () => {
    // Every household in the snapshot must be reachable from the account list;
    // a stray record would mean the capture crossed a tenant boundary.
    const ids = new Set(DEMO_ACCOUNTS.map((a) => a.id));
    for (const id of Object.keys(DEMO_HOUSEHOLDS)) {
      assert.ok(ids.has(id), `household ${id} is not in the account list — snapshot is inconsistent`);
    }
  });

  test('the book is not empty, or the preview would look broken', () => {
    assert.ok(DEMO_ACCOUNTS.length > 0);
    assert.ok(DEMO_POLICIES.length > 0);
    assert.ok(DEMO_TXNS.length > 0);
  });
});
